// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCocAlRrVZ6kLENO9VlgJW25npO-BvmqJU',
    appId: '1:322360016774:web:fcaa81d1aaf7c986263607',
    messagingSenderId: '322360016774',
    projectId: 'hmsi-app',
    authDomain: 'hmsi-app.firebaseapp.com',
    storageBucket: 'hmsi-app.appspot.com',
    measurementId: 'G-8BX3BSMX9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZUXLUUpCJFjYYgVowrJFEPgX6_NMw8NU',
    appId: '1:322360016774:android:4fc5ac43c24509d8263607',
    messagingSenderId: '322360016774',
    projectId: 'hmsi-app',
    storageBucket: 'hmsi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd6PW21hjkZsKA6w8Av2THv7Ds-8_qjEU',
    appId: '1:322360016774:ios:e46672a281ba4600263607',
    messagingSenderId: '322360016774',
    projectId: 'hmsi-app',
    storageBucket: 'hmsi-app.appspot.com',
    iosClientId: '322360016774-gr589dhcsehbalessp3krq27f3khumbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmsiApp',
  );
}
